### ISSUE TITLE
V3.20~33 white screen

### ISSUE THREAD

**Issue by thomasinaz41213** [kwindrem/GuiMods#212] opened 2023-12-07 23:41 UTC
I'm sure you're probably working on it already, but just in case... updated to 3.20~33 and got white screen. I'll roll back to 3.13 for now.

**Comment by kwindrem** [comment] 2023-12-08 00:42
I have seen this a couple of times on first boot after updating firmware. A reboot restored the GUI. 

I was able to reproduce the problem and it has something to do with SetupHelper (PackageManager). Looking into the cause and will fix it. 

For now, just reboot after a firmware update if running any packages that use SetupHelper!

**Comment by kwindrem** [comment] 2023-12-08 23:48
Should be fixed now in SetupHelper v5.16

**Closed by kwindrem** 2023-12-08 23:48 UTC
