### ISSUE TITLE
Missing data after update 

### ISSUE THREAD

**Issue by StupidMonkeyKev** [kwindrem/GuiMods#103] opened 2023-01-18 20:58 UTC
![2023-01-18 20 39 01](https://user-images.githubusercontent.com/123023691/213291231-32ce6cee-fb88-4cb5-b121-cdff04f77e94.jpg)

This is my issue, everything was fine till the cerbo updated, then went a bit wack - saw there was updates for setup helper and guimods but I just lost more on the display. I've tried going back to 2.92, no luck, swap to "victron stock" rather than DC coupled and AC input/output boxes come back but still no data for my DC, PV and inverter data/shore power.

Remove GuiMods and display is fine, DC, PV and inverter data/shore power all there on either cerbo firmware.

Any idea?  I've had a right good mess around and a couple of dozen reboots but I'm lost  and I REALLY like the Guimods :) Thanks for doing it for the community. and my current choice is see the temps with GuiMods or power data without

![2023-01-18 20 56 47](https://user-images.githubusercontent.com/123023691/213293085-d11482cf-e78f-4fb4-bd52-a6e1fde29f0a.jpg)

**Comment by kwindrem** [comment] 2023-01-18 22:22
Can you get to the logs? I'd be interested in the one for systemcalc as that's the only thing that might cause everything to disappear.

tail -50 /data/log/dbus-systemcalc-py/current | tai64nlocal

GuiMods is working fine here on my test RPI and a working system with Cerbo.

**Comment by kwindrem** [comment] 2023-01-18 23:40
You need terminal access either a direct serial connection or via ssh from another computer.

https://www.victronenergy.com/live/ccgx:root_access

Then:

tail -50 /data/log/dbus-systemcalc-py/current | tai64nlocal
tail -50 /data/log/PackageManager/current | tai64nlocal
tail -50 /data/log/SetupHelper | tai64nlocal

zip the results and post here.

PackageManager dumps the last two logs to a USB flash drive when doing a Settings backup, but not systemcalc which is the likely suspect in this case.

You could try uninstalling GuiMods and then SetupHelper, then INSTALLING v2.92 again (not selecting from the firmware backup) and reinstalling SetupHelper and GuiMods and see of the issue persists. If that succeeds, then try INSTALLING v3.00~15 again. Installing replaces all files in the working directories so you have a fresh image. This could resolve the issue if something got corrupted along the way.

**Comment by kwindrem** [comment] 2023-01-19 00:25
Let me know what devices you have connected to your Cerbo and I'll look over the code.

**Comment by StupidMonkeyKev** [comment] 2023-01-19 11:22
I'll try and do the command line stuff tonight, and get at the logs.

Cerbo GX with Multiplus compact 2000-80-30. VE bus connection to Cerbo GX
SOC/Battery via BMV-700 with VE direct connection from remote display to Cerbo
BMV-714??  smartshunt with bluetooth on a non-victron MPPT as a PV DC Power meter - VE direct cable shunt to Cerbo

And a touch 50 screnn

**Comment by rspott** [comment] 2023-01-19 12:48
<img width="513" alt="image" src="https://user-images.githubusercontent.com/17008510/213445390-3419b963-a2c8-459b-afc9-64381a7b9062.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/17008510/213445543-729ed0b9-d66c-4b86-81dc-3e2c5ab4b6ad.png">

Attached are the results of these commands:
  531  mkdir info
  532  cd info/
  534  cp  /data/log/PackageManager/current ./PackageManager-current
  535  cp /data/log/dbus-systemcalc-py/current ./dbus-systemcalc-py-current
  536  cp /data/log/SetupHelper ./SetupHelper
  541  cd ..
  542  tar cvfz info.tar.gz info/

[info.tar.gz](https://github.com/kwindrem/GuiMods/files/10456805/info.tar.gz)


I hope this helps. Thank you for doing all this work.

**Comment by rspott** [comment] 2023-01-19 12:50
I will need to uninstall so I can visualize the data on my system locally for a bit. 

I am GMT-5 if you need anything. Shoulder surfing etc.

**Comment by StupidMonkeyKev** [comment] 2023-01-19 16:03
[SetupHelper.zip](https://github.com/kwindrem/GuiMods/files/10458381/SetupHelper.zip)

Well it took me way too long to even find the IP for the Cerbo .....  but my old brain caught up and I think I've got that data here for you now.

**Comment by StupidMonkeyKev** [comment] 2023-01-19 16:16
[WITHGUIMODSINST.txt](https://github.com/kwindrem/GuiMods/files/10458493/WITHGUIMODSINST.txt)

Hopefully that helps - all 3 in 1 text file

**Comment by kwindrem** [comment] 2023-01-19 16:56
Thanks. Got what I need and know where the problem is. I'll get a fix out today.

**Comment by StupidMonkeyKev** [comment] 2023-01-19 18:17
![image](https://user-images.githubusercontent.com/123023691/213527072-edb54819-9ee1-46bf-ae64-caadc8e76a93.png)

Would appear to have fixed it, thank you

**Comment by IvanfromVenus** [comment] 2023-02-06 10:17
Hello,

After installing v7.13 I get the same or similar error - missing data. Both DC and Solar data are missing.
After installing the guimod, I see don't see anymore the shunt connection under settings/system setup/battery measurements/

<img width="805" alt="Screenshot 2023-02-06 at 12 10 55" src="https://user-images.githubusercontent.com/124571858/216945278-3782c564-91b5-4f82-9156-f6c3a6c6727f.png">
<img width="794" alt="Screenshot 2023-02-06 at 12 06 00" src="https://user-images.githubusercontent.com/124571858/216945828-0044f1ce-5794-4203-a3ae-665a592d6d84.png">
<img width="797" alt="Screenshot 2023-02-06 at 12 06 14" src="https://user-images.githubusercontent.com/124571858/216945839-9f0b93bb-ed07-4526-8193-eb1c533f1293.png">
<img width="809" alt="Screenshot 2023-02-06 at 11 03 26" src="https://user-images.githubusercontent.com/124571858/216945868-e2227e1a-9f2d-4c30-a507-14b6f6c8a353.png">
<img width="791" alt="Screenshot 2023-02-06 at 11 03 38" src="https://user-images.githubusercontent.com/124571858/216945874-cb05ba98-ca62-4da7-9055-fc283a8ea298.png">

**Comment by kwindrem** [comment] 2023-02-06 16:52
What Venus OS version?

Can you get to logs? You can do a PackageManager Settings backup which will create a log zip file on removable media that contains all log files. Post that file here and I'll take a look.

**Comment by IvanfromVenus** [comment] 2023-02-06 21:31
Venus OS version is 2.92. the log i will tomorrow

**Comment by IvanfromVenus** [comment] 2023-02-11 21:18
I updated the logs.

**Comment by kwindrem** [comment] 2023-02-12 06:36
The logs showed the problem. Will get a fix out tomorrow.

**Comment by kwindrem** [comment] 2023-02-12 17:24
Should be fixed now in v7.15.

**Closed** 2023-02-12 17:24 UTC
