### ISSUE TITLE
Generator-Mode Relay will not Open after Closing

### ISSUE THREAD

**Issue by iNotMario** [kwindrem/GuiMods#195] opened 2023-10-05 15:36 UTC
At some point in recent victron updates (3.10 is first official impacted release), an issue has arisen that seems to only occur with GUIMods installed... I do not know if there is any correlation with the GUI mods version.

If Relay 1 is closed while the relay is setup for generator control, the relay will never open again. The generator control screen will insist that it is no longer in run-mode, but the relay remains closed. You can get it to open by setting it to "manual" - or you can "uninstall" GuiMods with SetupHelper.

The effect of this is quite severe... any automated operation of a relay-controlled generator results in the generator turning on - but never turning back off until manual intervention.

I've verified the issue multiple times. It does not happen with Venus OS full-releases older than 3.10, and it does not happen with GUIMods uninstalled.

**Comment by cuisinartoh** [comment] 2023-10-05 18:05
GuiMods 8.10 & VenusOS 3.10

I can duplicate it. I just discovered this bug myself. If I change Relay 1 in VenusOS to a manual relay (instead of generator start/stop) then the relay behaves properly. If you change the relay type to generator you can manually start the generator (close the relay) but you can't manually stop the generator (open the relay). As soon as you set the relay type back to manual, the relay opens.

After uninstalling GuiMods 8.10 the problem goes away. There seems to be an error in the logic somewhere that isn't opening the relay properly when it's set to generator start/stop.

I don't know what data I can provide, but I have this vehicle for another hour at which time I'd have to rig up another test system to try and get you some data.

For now, I'm sending this vehicle out w/o GuiMods installed.

Thanks!

**Comment by kwindrem** [comment] 2023-10-05 18:20
The generator log would be useful:

/data/log/dbus-generator-starter/current

You can gather up all logs using the Backup settings option in PackageManager. This creates logs.zip on a USB flash drive which you can then post here.

I continue to test but can not duplicate the issue here.

**Comment by cuisinartoh** [comment] 2023-10-06 12:50
I decided not to modify a working system to get some logs. I had already uninstalled GuiMods so the customer could pick up their motorhome this morning. However, I have a commercial vehicle here with a 12kW generator on board I can test with next week. Yesterday I went through 25 stop/start cycles without any problems so I will have to first replicate the issue there.

**Comment by kwindrem** [comment] 2023-10-06 15:24
Were these test cycles on a system that had originally experienced the "stuck relay" problem?

When the problem does occur, is it every time the system is stopped or at random?

I found one section of my modified code that might have caused this problem but I never saw the problem here.

Can you confirm that the relay on the GX device is in fact not opening? That is, not basing your "stuck relay" issue on the fact that the generator continues to run?

In my tests here, I route the relay back to the generator digital input so the GX device can display the state of the relay. Doing this during testing could save wear and tear on your generator.

Thanks for continuing to provide feedback.

**Comment by cuisinartoh** [comment] 2023-10-06 16:02
Yes, we've noticed this issue on an RV and four mobile medical clinics we built. All use an Atkinson Electronics generator controller with Onan generators. We've isolated it to the relay configured in generator start/stop mode and only with the latest GuiMods installed. If you change the relay type to manual then the relay will release.

We disconnected the Atkinson controller and put a voltmeter on the C and NO contacts of relay 1 on the Cerbo and we can see that the relay isn't opening per above. 

It was only yesterday that I was able to isolate this to GuiMods 8.10. I assume it's a logic issue that isn't instructing the relay to open but does display on the GX Touch screen that the generator is "stopped". 

Thanks for your help with this!

**Comment by kwindrem** [comment] 2023-10-06 16:44
Thanks for the verification.

I have published a test version of GuiMods that may solve the stuck relay problem. You can get this version by setting the branch/tag for GuiMods to beta then downloading/installing.

**Comment by cuisinartoh** [comment] 2023-10-06 21:10
The customer who picked up their motorhome today is a sw developer so he
might be cool with trying it out. I will let you know. Thanks!
—
Ed Jones - K8MEJ - Lewis Center, Ohio U.S.A

"When I was sufficiently recovered to be permitted to take nourishment,
I felt the most extraordinary desire for a glass of Guinness...I am
confident that it contributed more than anything else to my recovery."
  - written by a wounded officer after Battle of Waterloo, 1815

**Comment by ivarw** [comment] 2023-10-06 23:14
I can confirm same issue with relay not opening on Stop tap while running GuiMods 8.10, VenusOS 3.10.
Uninstalling GuiMods solved the issue.
As per request, GuiMods were renstalled with branch/tag beta.
Conclusion after two test runs for this installation is that the "stuck relay" issue is solved under GuiMods 8.11~2.
Relay opens upon tapping stop. Generator shuts down. 
Well done!

**Comment by kwindrem** [comment] 2023-10-06 23:48
I've merged these changes into the released tag. Don't forget to set the GuiMods branch/tag back to 'latest'!

I can't explain why I did not see this issue here but glad it's working in the field.

Thank you for all your efforts in testing.

**Closed by kwindrem** 2023-10-06 23:48 UTC

**Comment by ivarw** [comment] 2023-10-07 00:08
8.11 is tested. It is golden!
Kudos, Bro.

**Comment by iNotMario** [comment] 2023-10-07 01:41
Confirmed resolved.

For the record, this bug affected any usage of the generator relay - manual, configured, or even node-red controlled.

**Comment by cuisinartoh** [comment] 2023-10-09 17:10
I, too, can confirm 8.11 solves the issue. Thanks for the quick fix!
